version: '3'

networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./backend/app:/var/www/project
            - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./backend/php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./backend/app:/var/www/project
        networks:
            - nginx-php74-mysql8-node
    
    mysql8-service:
        image: mysql:8.0.27
        container_name: mysql8-container
        ports:
          - "4306:3306"
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
          MYSQL_USER: christian
          MYSQL_ROOT_PASSWORD: secret
          MSYQL_PASSWORD: secret
        volumes:
            - ./backend/mysql:/var/lib/mysql
        networks:
            - nginx-php74-mysql8-node
            
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:5.1.1
        restart: 'always'
        ports:
          - '8087:80'
        environment:
          - PMA_HOST=mysql8-service
          - PMA_PASSWORD:secret
        depends_on:
          - mysql8-service
        links:
          - mysql8-service
    
    frontend:
      image: christianphp/dockerangular:1.0.0
      container_name: angular_node
      ports:
          - 8100:4200
      volumes:
          - "./app:/app"
          - "./app/node_modules:/app/node_modules"
          
      #tty: true
    

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php74-mysql8-node